[alias]
cg = "run --bin doodle -- format --output rust --dest generated/gencode.rs"
cgstat = "run --bin doodle -- format --output rust --stat-only --dest experiments/gencode_stat.rs"

[profile.profiling]
inherits = "release"
debug = true

[env]
RUST_MIN_STACK = "8388608"
